#include "key_code.h"

#include <GLFW/glfw3.h>

namespace blowbox
{
    //------------------------------------------------------------------------------------------------------
    KeyCode GlfwKeyToBlowboxKeyCode(int glfw_key)
    {
        KeyCode blowbox_key_code = KeyCode_UNKNOWN;
        switch (glfw_key)
        {
            case GLFW_KEY_SPACE:            blowbox_key_code = KeyCode_SPACE;           break;
            case GLFW_KEY_APOSTROPHE:       blowbox_key_code = KeyCode_APOSTROPHE;      break;
            case GLFW_KEY_COMMA:            blowbox_key_code = KeyCode_COMMA;           break;
            case GLFW_KEY_MINUS:            blowbox_key_code = KeyCode_MINUS;           break;
            case GLFW_KEY_PERIOD:           blowbox_key_code = KeyCode_PERIOD;          break;
            case GLFW_KEY_SLASH:            blowbox_key_code = KeyCode_SLASH;           break;
            case GLFW_KEY_0:                blowbox_key_code = KeyCode_0;               break;
            case GLFW_KEY_1:                blowbox_key_code = KeyCode_1;               break;
            case GLFW_KEY_2:                blowbox_key_code = KeyCode_2;               break;
            case GLFW_KEY_3:                blowbox_key_code = KeyCode_3;               break;
            case GLFW_KEY_4:                blowbox_key_code = KeyCode_4;               break;
            case GLFW_KEY_5:                blowbox_key_code = KeyCode_5;               break;
            case GLFW_KEY_6:                blowbox_key_code = KeyCode_6;               break;
            case GLFW_KEY_7:                blowbox_key_code = KeyCode_7;               break;
            case GLFW_KEY_8:                blowbox_key_code = KeyCode_8;               break;
            case GLFW_KEY_9:                blowbox_key_code = KeyCode_9;               break;
            case GLFW_KEY_SEMICOLON:        blowbox_key_code = KeyCode_SEMICOLON;       break;
            case GLFW_KEY_EQUAL:            blowbox_key_code = KeyCode_EQUAL;           break;
            case GLFW_KEY_A:                blowbox_key_code = KeyCode_A;               break;
            case GLFW_KEY_B:                blowbox_key_code = KeyCode_B;               break;
            case GLFW_KEY_C:                blowbox_key_code = KeyCode_C;               break;
            case GLFW_KEY_D:                blowbox_key_code = KeyCode_D;               break;
            case GLFW_KEY_E:                blowbox_key_code = KeyCode_E;               break;
            case GLFW_KEY_F:                blowbox_key_code = KeyCode_F;               break;
            case GLFW_KEY_G:                blowbox_key_code = KeyCode_G;               break;
            case GLFW_KEY_H:                blowbox_key_code = KeyCode_H;               break;
            case GLFW_KEY_I:                blowbox_key_code = KeyCode_I;               break;
            case GLFW_KEY_J:                blowbox_key_code = KeyCode_J;               break;
            case GLFW_KEY_K:                blowbox_key_code = KeyCode_K;               break;
            case GLFW_KEY_L:                blowbox_key_code = KeyCode_L;               break;
            case GLFW_KEY_M:                blowbox_key_code = KeyCode_M;               break;
            case GLFW_KEY_N:                blowbox_key_code = KeyCode_N;               break;
            case GLFW_KEY_O:                blowbox_key_code = KeyCode_O;               break;
            case GLFW_KEY_P:                blowbox_key_code = KeyCode_P;               break;
            case GLFW_KEY_Q:                blowbox_key_code = KeyCode_Q;               break;
            case GLFW_KEY_R:                blowbox_key_code = KeyCode_R;               break;
            case GLFW_KEY_S:                blowbox_key_code = KeyCode_S;               break;
            case GLFW_KEY_T:                blowbox_key_code = KeyCode_T;               break;
            case GLFW_KEY_U:                blowbox_key_code = KeyCode_U;               break;
            case GLFW_KEY_V:                blowbox_key_code = KeyCode_V;               break;
            case GLFW_KEY_W:                blowbox_key_code = KeyCode_W;               break;
            case GLFW_KEY_X:                blowbox_key_code = KeyCode_X;               break;
            case GLFW_KEY_Y:                blowbox_key_code = KeyCode_Y;               break;
            case GLFW_KEY_Z:                blowbox_key_code = KeyCode_Z;               break;
            case GLFW_KEY_LEFT_BRACKET:     blowbox_key_code = KeyCode_LEFT_BRACKET;    break;
            case GLFW_KEY_BACKSLASH:        blowbox_key_code = KeyCode_BACKSLASH;       break;
            case GLFW_KEY_RIGHT_BRACKET:    blowbox_key_code = KeyCode_RIGHT_BRACKET;   break;
            case GLFW_KEY_GRAVE_ACCENT:     blowbox_key_code = KeyCode_GRAVE_ACCENT;    break;
            case GLFW_KEY_WORLD_1:          blowbox_key_code = KeyCode_WORLD_1;         break;
            case GLFW_KEY_WORLD_2:          blowbox_key_code = KeyCode_WORLD_2;         break;
            case GLFW_KEY_ESCAPE:           blowbox_key_code = KeyCode_ESCAPE;          break;
            case GLFW_KEY_ENTER:            blowbox_key_code = KeyCode_ENTER;           break;
            case GLFW_KEY_TAB:              blowbox_key_code = KeyCode_TAB;             break;
            case GLFW_KEY_BACKSPACE:        blowbox_key_code = KeyCode_BACKSPACE;       break;
            case GLFW_KEY_INSERT:           blowbox_key_code = KeyCode_INSERT;          break;
            case GLFW_KEY_DELETE:           blowbox_key_code = KeyCode_DELETE;          break;
            case GLFW_KEY_RIGHT:            blowbox_key_code = KeyCode_RIGHT;           break;
            case GLFW_KEY_LEFT:             blowbox_key_code = KeyCode_LEFT;            break;
            case GLFW_KEY_DOWN:             blowbox_key_code = KeyCode_DOWN;            break;
            case GLFW_KEY_UP:               blowbox_key_code = KeyCode_UP;              break;
            case GLFW_KEY_PAGE_UP:          blowbox_key_code = KeyCode_PAGE_UP;         break;
            case GLFW_KEY_PAGE_DOWN:        blowbox_key_code = KeyCode_PAGE_DOWN;       break;
            case GLFW_KEY_HOME:             blowbox_key_code = KeyCode_HOME;            break;
            case GLFW_KEY_END:              blowbox_key_code = KeyCode_END;             break;
            case GLFW_KEY_CAPS_LOCK:        blowbox_key_code = KeyCode_CAPS_LOCK;       break;
            case GLFW_KEY_SCROLL_LOCK:      blowbox_key_code = KeyCode_SCROLL_LOCK;     break;
            case GLFW_KEY_NUM_LOCK:         blowbox_key_code = KeyCode_NUM_LOCK;        break;
            case GLFW_KEY_PRINT_SCREEN:     blowbox_key_code = KeyCode_PRINT_SCREEN;    break;
            case GLFW_KEY_PAUSE:            blowbox_key_code = KeyCode_PAUSE;           break;
            case GLFW_KEY_F1:               blowbox_key_code = KeyCode_F1;              break;
            case GLFW_KEY_F2:               blowbox_key_code = KeyCode_F2;              break;
            case GLFW_KEY_F3:               blowbox_key_code = KeyCode_F3;              break;
            case GLFW_KEY_F4:               blowbox_key_code = KeyCode_F4;              break;
            case GLFW_KEY_F5:               blowbox_key_code = KeyCode_F5;              break;
            case GLFW_KEY_F6:               blowbox_key_code = KeyCode_F6;              break;
            case GLFW_KEY_F7:               blowbox_key_code = KeyCode_F7;              break;
            case GLFW_KEY_F8:               blowbox_key_code = KeyCode_F8;              break;
            case GLFW_KEY_F9:               blowbox_key_code = KeyCode_F9;              break;
            case GLFW_KEY_F10:              blowbox_key_code = KeyCode_F10;             break;
            case GLFW_KEY_F11:              blowbox_key_code = KeyCode_F11;             break;
            case GLFW_KEY_F12:              blowbox_key_code = KeyCode_F12;             break;
            case GLFW_KEY_F13:              blowbox_key_code = KeyCode_F13;             break;
            case GLFW_KEY_F14:              blowbox_key_code = KeyCode_F14;             break;
            case GLFW_KEY_F15:              blowbox_key_code = KeyCode_F15;             break;
            case GLFW_KEY_F16:              blowbox_key_code = KeyCode_F16;             break;
            case GLFW_KEY_F17:              blowbox_key_code = KeyCode_F17;             break;
            case GLFW_KEY_F18:              blowbox_key_code = KeyCode_F18;             break;
            case GLFW_KEY_F19:              blowbox_key_code = KeyCode_F19;             break;
            case GLFW_KEY_F20:              blowbox_key_code = KeyCode_F20;             break;
            case GLFW_KEY_F21:              blowbox_key_code = KeyCode_F21;             break;
            case GLFW_KEY_F22:              blowbox_key_code = KeyCode_F22;             break;
            case GLFW_KEY_F23:              blowbox_key_code = KeyCode_F23;             break;
            case GLFW_KEY_F24:              blowbox_key_code = KeyCode_F24;             break;
            case GLFW_KEY_F25:              blowbox_key_code = KeyCode_F25;             break;
            case GLFW_KEY_KP_0:             blowbox_key_code = KeyCode_KP_0;            break;
            case GLFW_KEY_KP_1:             blowbox_key_code = KeyCode_KP_1;            break;
            case GLFW_KEY_KP_2:             blowbox_key_code = KeyCode_KP_2;            break;
            case GLFW_KEY_KP_3:             blowbox_key_code = KeyCode_KP_3;            break;
            case GLFW_KEY_KP_4:             blowbox_key_code = KeyCode_KP_4;            break;
            case GLFW_KEY_KP_5:             blowbox_key_code = KeyCode_KP_5;            break;
            case GLFW_KEY_KP_6:             blowbox_key_code = KeyCode_KP_6;            break;
            case GLFW_KEY_KP_7:             blowbox_key_code = KeyCode_KP_7;            break;
            case GLFW_KEY_KP_8:             blowbox_key_code = KeyCode_KP_8;            break;
            case GLFW_KEY_KP_9:             blowbox_key_code = KeyCode_KP_9;            break;
            case GLFW_KEY_KP_DECIMAL:       blowbox_key_code = KeyCode_KP_DECIMAL;      break;
            case GLFW_KEY_KP_DIVIDE:        blowbox_key_code = KeyCode_KP_DIVIDE;       break;
            case GLFW_KEY_KP_MULTIPLY:      blowbox_key_code = KeyCode_KP_MULTIPLY;     break;
            case GLFW_KEY_KP_SUBTRACT:      blowbox_key_code = KeyCode_KP_SUBTRACT;     break;
            case GLFW_KEY_KP_ADD:           blowbox_key_code = KeyCode_KP_ADD;          break;
            case GLFW_KEY_KP_ENTER:         blowbox_key_code = KeyCode_KP_ENTER;        break;
            case GLFW_KEY_KP_EQUAL:         blowbox_key_code = KeyCode_KP_EQUAL;        break;
            case GLFW_KEY_LEFT_SHIFT:       blowbox_key_code = KeyCode_LEFT_SHIFT;      break;
            case GLFW_KEY_LEFT_CONTROL:     blowbox_key_code = KeyCode_LEFT_CONTROL;    break;
            case GLFW_KEY_LEFT_ALT:         blowbox_key_code = KeyCode_LEFT_ALT;        break;
            case GLFW_KEY_LEFT_SUPER:       blowbox_key_code = KeyCode_LEFT_SUPER;      break;
            case GLFW_KEY_RIGHT_SHIFT:      blowbox_key_code = KeyCode_RIGHT_SHIFT;     break;
            case GLFW_KEY_RIGHT_CONTROL:    blowbox_key_code = KeyCode_RIGHT_CONTROL;   break;
            case GLFW_KEY_RIGHT_ALT:        blowbox_key_code = KeyCode_RIGHT_ALT;       break;
            case GLFW_KEY_RIGHT_SUPER:      blowbox_key_code = KeyCode_RIGHT_SUPER;     break;
            case GLFW_KEY_MENU:             blowbox_key_code = KeyCode_MENU;            break;
        }

        return blowbox_key_code;
    }

    //------------------------------------------------------------------------------------------------------
    int BlowboxKeyCodeToGlfwKey(KeyCode key)
    {
        int glfw_key = GLFW_KEY_UNKNOWN;
        switch (key)
        {
            case KeyCode_SPACE:                 glfw_key = GLFW_KEY_SPACE;          break;
            case KeyCode_APOSTROPHE:            glfw_key = GLFW_KEY_APOSTROPHE;     break;
            case KeyCode_COMMA:                 glfw_key = GLFW_KEY_COMMA;          break;
            case KeyCode_MINUS:                 glfw_key = GLFW_KEY_MINUS;          break;
            case KeyCode_PERIOD:                glfw_key = GLFW_KEY_PERIOD;         break;
            case KeyCode_SLASH:                 glfw_key = GLFW_KEY_SLASH;          break;
            case KeyCode_0:                     glfw_key = GLFW_KEY_0;              break;
            case KeyCode_1:                     glfw_key = GLFW_KEY_1;              break;
            case KeyCode_2:                     glfw_key = GLFW_KEY_2;              break;
            case KeyCode_3:                     glfw_key = GLFW_KEY_3;              break;
            case KeyCode_4:                     glfw_key = GLFW_KEY_4;              break;
            case KeyCode_5:                     glfw_key = GLFW_KEY_5;              break;
            case KeyCode_6:                     glfw_key = GLFW_KEY_6;              break;
            case KeyCode_7:                     glfw_key = GLFW_KEY_7;              break;
            case KeyCode_8:                     glfw_key = GLFW_KEY_8;              break;
            case KeyCode_9:                     glfw_key = GLFW_KEY_9;              break;
            case KeyCode_SEMICOLON:             glfw_key = GLFW_KEY_SEMICOLON;      break;
            case KeyCode_EQUAL:                 glfw_key = GLFW_KEY_EQUAL;          break;
            case KeyCode_A:                     glfw_key = GLFW_KEY_A;              break;
            case KeyCode_B:                     glfw_key = GLFW_KEY_B;              break;
            case KeyCode_C:                     glfw_key = GLFW_KEY_C;              break;
            case KeyCode_D:                     glfw_key = GLFW_KEY_D;              break;
            case KeyCode_E:                     glfw_key = GLFW_KEY_E;              break;
            case KeyCode_F:                     glfw_key = GLFW_KEY_F;              break;
            case KeyCode_G:                     glfw_key = GLFW_KEY_G;              break;
            case KeyCode_H:                     glfw_key = GLFW_KEY_H;              break;
            case KeyCode_I:                     glfw_key = GLFW_KEY_I;              break;
            case KeyCode_J:                     glfw_key = GLFW_KEY_J;              break;
            case KeyCode_K:                     glfw_key = GLFW_KEY_K;              break;
            case KeyCode_L:                     glfw_key = GLFW_KEY_L;              break;
            case KeyCode_M:                     glfw_key = GLFW_KEY_M;              break;
            case KeyCode_N:                     glfw_key = GLFW_KEY_N;              break;
            case KeyCode_O:                     glfw_key = GLFW_KEY_O;              break;
            case KeyCode_P:                     glfw_key = GLFW_KEY_P;              break;
            case KeyCode_Q:                     glfw_key = GLFW_KEY_Q;              break;
            case KeyCode_R:                     glfw_key = GLFW_KEY_R;              break;
            case KeyCode_S:                     glfw_key = GLFW_KEY_S;              break;
            case KeyCode_T:                     glfw_key = GLFW_KEY_T;              break;
            case KeyCode_U:                     glfw_key = GLFW_KEY_U;              break;
            case KeyCode_V:                     glfw_key = GLFW_KEY_V;              break;
            case KeyCode_W:                     glfw_key = GLFW_KEY_W;              break;
            case KeyCode_X:                     glfw_key = GLFW_KEY_X;              break;
            case KeyCode_Y:                     glfw_key = GLFW_KEY_Y;              break;
            case KeyCode_Z:                     glfw_key = GLFW_KEY_Z;              break;
            case KeyCode_LEFT_BRACKET:          glfw_key = GLFW_KEY_LEFT_BRACKET;   break;
            case KeyCode_BACKSLASH:             glfw_key = GLFW_KEY_BACKSLASH;      break;
            case KeyCode_RIGHT_BRACKET:         glfw_key = GLFW_KEY_RIGHT_BRACKET;  break;
            case KeyCode_GRAVE_ACCENT:          glfw_key = GLFW_KEY_GRAVE_ACCENT;   break;
            case KeyCode_WORLD_1:               glfw_key = GLFW_KEY_WORLD_1;        break;
            case KeyCode_WORLD_2:               glfw_key = GLFW_KEY_WORLD_2;        break;
            case KeyCode_ESCAPE:                glfw_key = GLFW_KEY_ESCAPE;         break;
            case KeyCode_ENTER:                 glfw_key = GLFW_KEY_ENTER;          break;
            case KeyCode_TAB:                   glfw_key = GLFW_KEY_TAB;            break;
            case KeyCode_BACKSPACE:             glfw_key = GLFW_KEY_BACKSPACE;      break;
            case KeyCode_INSERT:                glfw_key = GLFW_KEY_INSERT;         break;
            case KeyCode_DELETE:                glfw_key = GLFW_KEY_DELETE;         break;
            case KeyCode_RIGHT:                 glfw_key = GLFW_KEY_RIGHT;          break;
            case KeyCode_LEFT:                  glfw_key = GLFW_KEY_LEFT;           break;
            case KeyCode_DOWN:                  glfw_key = GLFW_KEY_DOWN;           break;
            case KeyCode_UP:                    glfw_key = GLFW_KEY_UP;             break;
            case KeyCode_PAGE_UP:               glfw_key = GLFW_KEY_PAGE_UP;        break;
            case KeyCode_PAGE_DOWN:             glfw_key = GLFW_KEY_PAGE_DOWN;      break;
            case KeyCode_HOME:                  glfw_key = GLFW_KEY_HOME;           break;
            case KeyCode_END:                   glfw_key = GLFW_KEY_END;            break;
            case KeyCode_CAPS_LOCK:             glfw_key = GLFW_KEY_CAPS_LOCK;      break;
            case KeyCode_SCROLL_LOCK:           glfw_key = GLFW_KEY_SCROLL_LOCK;    break;
            case KeyCode_NUM_LOCK:              glfw_key = GLFW_KEY_NUM_LOCK;       break;
            case KeyCode_PRINT_SCREEN:          glfw_key = GLFW_KEY_PRINT_SCREEN;   break;
            case KeyCode_PAUSE:                 glfw_key = GLFW_KEY_PAUSE;          break;
            case KeyCode_F1:                    glfw_key = GLFW_KEY_F1;             break;
            case KeyCode_F2:                    glfw_key = GLFW_KEY_F2;             break;
            case KeyCode_F3:                    glfw_key = GLFW_KEY_F3;             break;
            case KeyCode_F4:                    glfw_key = GLFW_KEY_F4;             break;
            case KeyCode_F5:                    glfw_key = GLFW_KEY_F5;             break;
            case KeyCode_F6:                    glfw_key = GLFW_KEY_F6;             break;
            case KeyCode_F7:                    glfw_key = GLFW_KEY_F7;             break;
            case KeyCode_F8:                    glfw_key = GLFW_KEY_F8;             break;
            case KeyCode_F9:                    glfw_key = GLFW_KEY_F9;             break;
            case KeyCode_F10:                   glfw_key = GLFW_KEY_F10;            break;
            case KeyCode_F11:                   glfw_key = GLFW_KEY_F11;            break;
            case KeyCode_F12:                   glfw_key = GLFW_KEY_F12;            break;
            case KeyCode_F13:                   glfw_key = GLFW_KEY_F13;            break;
            case KeyCode_F14:                   glfw_key = GLFW_KEY_F14;            break;
            case KeyCode_F15:                   glfw_key = GLFW_KEY_F15;            break;
            case KeyCode_F16:                   glfw_key = GLFW_KEY_F16;            break;
            case KeyCode_F17:                   glfw_key = GLFW_KEY_F17;            break;
            case KeyCode_F18:                   glfw_key = GLFW_KEY_F18;            break;
            case KeyCode_F19:                   glfw_key = GLFW_KEY_F19;            break;
            case KeyCode_F20:                   glfw_key = GLFW_KEY_F20;            break;
            case KeyCode_F21:                   glfw_key = GLFW_KEY_F21;            break;
            case KeyCode_F22:                   glfw_key = GLFW_KEY_F22;            break;
            case KeyCode_F23:                   glfw_key = GLFW_KEY_F23;            break;
            case KeyCode_F24:                   glfw_key = GLFW_KEY_F24;            break;
            case KeyCode_F25:                   glfw_key = GLFW_KEY_F25;            break;
            case KeyCode_KP_0:                  glfw_key = GLFW_KEY_KP_0;           break;
            case KeyCode_KP_1:                  glfw_key = GLFW_KEY_KP_1;           break;
            case KeyCode_KP_2:                  glfw_key = GLFW_KEY_KP_2;           break;
            case KeyCode_KP_3:                  glfw_key = GLFW_KEY_KP_3;           break;
            case KeyCode_KP_4:                  glfw_key = GLFW_KEY_KP_4;           break;
            case KeyCode_KP_5:                  glfw_key = GLFW_KEY_KP_5;           break;
            case KeyCode_KP_6:                  glfw_key = GLFW_KEY_KP_6;           break;
            case KeyCode_KP_7:                  glfw_key = GLFW_KEY_KP_7;           break;
            case KeyCode_KP_8:                  glfw_key = GLFW_KEY_KP_8;           break;
            case KeyCode_KP_9:                  glfw_key = GLFW_KEY_KP_9;           break;
            case KeyCode_KP_DECIMAL:            glfw_key = GLFW_KEY_KP_DECIMAL;     break;
            case KeyCode_KP_DIVIDE:             glfw_key = GLFW_KEY_KP_DIVIDE;      break;
            case KeyCode_KP_MULTIPLY:           glfw_key = GLFW_KEY_KP_MULTIPLY;    break;
            case KeyCode_KP_SUBTRACT:           glfw_key = GLFW_KEY_KP_SUBTRACT;    break;
            case KeyCode_KP_ADD:                glfw_key = GLFW_KEY_KP_ADD;         break;
            case KeyCode_KP_ENTER:              glfw_key = GLFW_KEY_KP_ENTER;       break;
            case KeyCode_KP_EQUAL:              glfw_key = GLFW_KEY_KP_EQUAL;       break;
            case KeyCode_LEFT_SHIFT:            glfw_key = GLFW_KEY_LEFT_SHIFT;     break;
            case KeyCode_LEFT_CONTROL:          glfw_key = GLFW_KEY_LEFT_CONTROL;   break;
            case KeyCode_LEFT_ALT:              glfw_key = GLFW_KEY_LEFT_ALT;       break;
            case KeyCode_LEFT_SUPER:            glfw_key = GLFW_KEY_LEFT_SUPER;     break;
            case KeyCode_RIGHT_SHIFT:           glfw_key = GLFW_KEY_RIGHT_SHIFT;    break;
            case KeyCode_RIGHT_CONTROL:         glfw_key = GLFW_KEY_RIGHT_CONTROL;  break;
            case KeyCode_RIGHT_ALT:             glfw_key = GLFW_KEY_RIGHT_ALT;      break;
            case KeyCode_RIGHT_SUPER:           glfw_key = GLFW_KEY_RIGHT_SUPER;    break;
            case KeyCode_MENU:                  glfw_key = GLFW_KEY_MENU;           break;
        }

        return glfw_key;
    }
}