#pragma once

#include <GLFW/glfw3.h>

namespace blowbox
{
    /**
    * This enumeration is to enumerate all different key codes that Blowbox supports.
    *
    * @brief All keycodes
    */
    enum KeyCode
    {
        KeyCode_SPACE               = GLFW_KEY_SPACE,
        KeyCode_APOSTROPHE          = GLFW_KEY_APOSTROPHE,
        KeyCode_COMMA               = GLFW_KEY_COMMA,
        KeyCode_MINUS               = GLFW_KEY_MINUS,
        KeyCode_PERIOD              = GLFW_KEY_PERIOD,
        KeyCode_SLASH               = GLFW_KEY_SLASH,
        KeyCode_0                   = GLFW_KEY_0,
        KeyCode_1                   = GLFW_KEY_1,
        KeyCode_2                   = GLFW_KEY_2,
        KeyCode_3                   = GLFW_KEY_3,
        KeyCode_4                   = GLFW_KEY_4,
        KeyCode_5                   = GLFW_KEY_5,
        KeyCode_6                   = GLFW_KEY_6,
        KeyCode_7                   = GLFW_KEY_7,
        KeyCode_8                   = GLFW_KEY_8,
        KeyCode_9                   = GLFW_KEY_9,
        KeyCode_SEMICOLON           = GLFW_KEY_SEMICOLON,
        KeyCode_EQUAL               = GLFW_KEY_EQUAL,
        KeyCode_A                   = GLFW_KEY_A,
        KeyCode_B                   = GLFW_KEY_B,
        KeyCode_C                   = GLFW_KEY_C,
        KeyCode_D                   = GLFW_KEY_D,
        KeyCode_E                   = GLFW_KEY_E,
        KeyCode_F                   = GLFW_KEY_F,
        KeyCode_G                   = GLFW_KEY_G,
        KeyCode_H                   = GLFW_KEY_H,
        KeyCode_I                   = GLFW_KEY_I,
        KeyCode_J                   = GLFW_KEY_J,
        KeyCode_K                   = GLFW_KEY_K,
        KeyCode_L                   = GLFW_KEY_L,
        KeyCode_M                   = GLFW_KEY_M,
        KeyCode_N                   = GLFW_KEY_N,
        KeyCode_O                   = GLFW_KEY_O,
        KeyCode_P                   = GLFW_KEY_P,
        KeyCode_Q                   = GLFW_KEY_Q,
        KeyCode_R                   = GLFW_KEY_R,
        KeyCode_S                   = GLFW_KEY_S,
        KeyCode_T                   = GLFW_KEY_T,
        KeyCode_U                   = GLFW_KEY_U,
        KeyCode_V                   = GLFW_KEY_V,
        KeyCode_W                   = GLFW_KEY_W,
        KeyCode_X                   = GLFW_KEY_X,
        KeyCode_Y                   = GLFW_KEY_Y,
        KeyCode_Z                   = GLFW_KEY_Z,
        KeyCode_LEFT_BRACKET        = GLFW_KEY_LEFT_BRACKET,
        KeyCode_BACKSLASH           = GLFW_KEY_BACKSLASH,
        KeyCode_RIGHT_BRACKET       = GLFW_KEY_RIGHT_BRACKET,
        KeyCode_GRAVE_ACCENT        = GLFW_KEY_GRAVE_ACCENT,
        KeyCode_WORLD_1             = GLFW_KEY_WORLD_1,
        KeyCode_WORLD_2             = GLFW_KEY_WORLD_2,
        KeyCode_ESCAPE              = GLFW_KEY_ESCAPE,
        KeyCode_ENTER               = GLFW_KEY_ENTER,
        KeyCode_TAB                 = GLFW_KEY_TAB,
        KeyCode_BACKSPACE           = GLFW_KEY_BACKSPACE,
        KeyCode_INSERT              = GLFW_KEY_INSERT,
        KeyCode_DELETE              = GLFW_KEY_DELETE,
        KeyCode_RIGHT               = GLFW_KEY_RIGHT,
        KeyCode_LEFT                = GLFW_KEY_LEFT,
        KeyCode_DOWN                = GLFW_KEY_DOWN,
        KeyCode_UP                  = GLFW_KEY_UP,
        KeyCode_PAGE_UP             = GLFW_KEY_PAGE_UP,
        KeyCode_PAGE_DOWN           = GLFW_KEY_PAGE_DOWN,
        KeyCode_HOME                = GLFW_KEY_HOME,
        KeyCode_END                 = GLFW_KEY_END,
        KeyCode_CAPS_LOCK           = GLFW_KEY_CAPS_LOCK,
        KeyCode_SCROLL_LOCK         = GLFW_KEY_SCROLL_LOCK,
        KeyCode_NUM_LOCK            = GLFW_KEY_NUM_LOCK,
        KeyCode_PRINT_SCREEN        = GLFW_KEY_PRINT_SCREEN,
        KeyCode_PAUSE               = GLFW_KEY_PAUSE,
        KeyCode_F1                  = GLFW_KEY_F1,
        KeyCode_F2                  = GLFW_KEY_F2,
        KeyCode_F3                  = GLFW_KEY_F3,
        KeyCode_F4                  = GLFW_KEY_F4,
        KeyCode_F5                  = GLFW_KEY_F5,
        KeyCode_F6                  = GLFW_KEY_F6,
        KeyCode_F7                  = GLFW_KEY_F7,
        KeyCode_F8                  = GLFW_KEY_F8,
        KeyCode_F9                  = GLFW_KEY_F9,
        KeyCode_F10                 = GLFW_KEY_F10,
        KeyCode_F11                 = GLFW_KEY_F11,
        KeyCode_F12                 = GLFW_KEY_F12,
        KeyCode_F13                 = GLFW_KEY_F13,
        KeyCode_F14                 = GLFW_KEY_F14,
        KeyCode_F15                 = GLFW_KEY_F15,
        KeyCode_F16                 = GLFW_KEY_F16,
        KeyCode_F17                 = GLFW_KEY_F17,
        KeyCode_F18                 = GLFW_KEY_F18,
        KeyCode_F19                 = GLFW_KEY_F19,
        KeyCode_F20                 = GLFW_KEY_F20,
        KeyCode_F21                 = GLFW_KEY_F21,
        KeyCode_F22                 = GLFW_KEY_F22,
        KeyCode_F23                 = GLFW_KEY_F23,
        KeyCode_F24                 = GLFW_KEY_F24,
        KeyCode_F25                 = GLFW_KEY_F25,
        KeyCode_KP_0                = GLFW_KEY_KP_0,
        KeyCode_KP_1                = GLFW_KEY_KP_1,
        KeyCode_KP_2                = GLFW_KEY_KP_2,
        KeyCode_KP_3                = GLFW_KEY_KP_3,
        KeyCode_KP_4                = GLFW_KEY_KP_4,
        KeyCode_KP_5                = GLFW_KEY_KP_5,
        KeyCode_KP_6                = GLFW_KEY_KP_6,
        KeyCode_KP_7                = GLFW_KEY_KP_7,
        KeyCode_KP_8                = GLFW_KEY_KP_8,
        KeyCode_KP_9                = GLFW_KEY_KP_9,
        KeyCode_KP_DECIMAL          = GLFW_KEY_KP_DECIMAL,
        KeyCode_KP_DIVIDE           = GLFW_KEY_KP_DIVIDE,
        KeyCode_KP_MULTIPLY         = GLFW_KEY_KP_MULTIPLY,
        KeyCode_KP_SUBTRACT         = GLFW_KEY_KP_SUBTRACT,
        KeyCode_KP_ADD              = GLFW_KEY_KP_ADD,
        KeyCode_KP_ENTER            = GLFW_KEY_KP_ENTER,
        KeyCode_KP_EQUAL            = GLFW_KEY_KP_EQUAL,
        KeyCode_LEFT_SHIFT          = GLFW_KEY_LEFT_SHIFT,
        KeyCode_LEFT_CONTROL        = GLFW_KEY_LEFT_CONTROL,
        KeyCode_LEFT_ALT            = GLFW_KEY_LEFT_ALT,
        KeyCode_LEFT_SUPER          = GLFW_KEY_LEFT_SUPER,
        KeyCode_RIGHT_SHIFT         = GLFW_KEY_RIGHT_SHIFT,
        KeyCode_RIGHT_CONTROL       = GLFW_KEY_RIGHT_CONTROL,
        KeyCode_RIGHT_ALT           = GLFW_KEY_RIGHT_ALT,
        KeyCode_RIGHT_SUPER         = GLFW_KEY_RIGHT_SUPER,
        KeyCode_MENU                = GLFW_KEY_MENU,
        KeyCode_UNKNOWN
    };

    /**
    * @brief Converts a GLFW_KEY_* to a KeyCode_*
    * @param[in] glfw_key A GLFW_KEY that you want to convert to a blowbox::KeyCode
    */
    KeyCode GlfwKeyToBlowboxKeyCode(int glfw_key);

    /**
    * @brief Converts a KeyCode_* to a GLFW_KEY_*
    * @param[in] key A blowbox::KeyCode that should be converted to a GLFW_KEY
    */
    int BlowboxKeyCodeToGlfwKey(KeyCode key);
}